### PR TITLE
scrolling questions for mobile

### PR DESCRIPTION
**Pull request by mkandler**
@cmacrander - these changes are the ones I was working on for the CTA qualtrics survey.  Mostly just moving around checkboxes and radio buttons on mobile & the big part is the scrolling in those `InnerInner` divs.

### CODE REVIEW

**Comment by cmacrander** [comment]
Looks simple enough! What testing did you do? Android? iOS? Desktop?

**Comment by mkandler** [comment]
I tested it using the iOS and Andriod simulators on Chrome.  Right now those changes are in the extra styles added to the survey but I'd like to test this modified file directly.  Is it possible to push these changes and test with the new file w/o affecting Yellowstone?

**Comment by cmacrander** [comment]
Sure. We can pull this commit into yellowstone-dev and point the survey at that file instead of perts.net.

**Comment by mkandler** [comment]
@cmacrander - updated after testing yesterday.  Any chance you could do your magic again?

**Comment by cmacrander** [comment]
I can and will! FYI, it involves these steps:
1. cd ~/Sites/yellowstone/static/silk
2. At this point you act as if you’re in a separate repository: git
   checkout scrolling and git pull
3. Then commit and push yellowstone to deploy the change: cd ../.. git
   commit -a git push

​

**Comment by mkandler** [comment]
Had to revert some changes after testing on an actual iphone... also to do the update myself I'm still a little confused by the process.  Do I need to do "git init" and everything within the silk directory?

**Comment by mkandler** [comment]
@cmacrander - could you pull this into yellowstone `dev` again? Or could you walk me through that?  This should be the last change and then we can have happy Qualtrics users.

**Comment by cmacrander** [comment]
Re: testing iOS, XCode has a 100% accurate emulator built into it, called Simulator, which has the bonus of being nice and fast (unlike browserstack). You can also use web tools on it by having Safari open at the same time. I can show you how to get that going, just make sure you have XCode first, b/c that's time consuming to install.

**Comment by mkandler** [comment]
Thanks Chris - I've used that simulator in the past, but my computer is basically a garbage dumpster zombie at this point and running XCode will probably crash it :(

**Comment by cmacrander** [comment]
http://img15.deviantart.net/27e7/i/2011/279/f/5/zombie_dumpster_by_memnalar-d4bz4ck.jpg

**Pull request merged**
